# مقدمه {.unnumbered}


بعد از ده  سال تجربه تدریس در دانشگاه به این نتیجه رسیدم که، ضعف دانشجویان در درس‌های ریاضییات همچون: **ریاضی عمومی ۱ و ۲ ، معادلات دیفرانسیل، ریاضیات گسسته، ریاضیات مهندسی و آمار و احتمال و ... ** به عدم درک عمیق مفاهیمی برمی‌گردد که در ریاضیات دبیرستانی آموزش داده شده اند.



خوشبختانه آنچه که یک دانشجو برای یادگیری مطالب ریاضی در سطح دانشگاهی نیاز دارد به طور تمام و کمال در ریاضیات دبیرستانی به آن پرداخته شده است.

در این کتاب من قصد دارم تمامی مطالب گفته شده در کتاب‌های دبیرستانی را به طور منسجم تحت عنوان ریاضیات پیش دانشگاهی برای دانشجویان یادآوری کنم. درصد خیلی کمی از مطالب ممکن است جدید باشد و همچنین درصد بسیار اندکی از مطالب غیر ضروری مطرح شده در کتاب‌های دبیرستانی حذف شده‌اند.

جهت هر گونه پرسش و یا همکاری لطفا از [صفحه تماس با من](https://www.samyar.de/contact) اقدام کنید. 


## طرح کتاب {.unnumbered}

1.	نظریه مجموعه
2.	دستگاه حقیقی
3.	عبارتهای جبری
4.	معادلات
5.	نامعادلات
6.	دستگاه معادلات
7.	تجزیه کسرها
8.	دستگاه دکارتی
9.	مثلثات
10.	تابع
11.	تابع نمایی
12.	تابع مثلثاتی